# Generated by Django 6.1.1 on 2026-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('maquina', models.CharField(max_length=100)),
                ('sintoma', models.TextField()),
                ('tecnico_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio_parada', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_parada', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
