# Generated by Django 6.1.1 on 2026-09-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_fin_parada',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_inicio_parada',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fin_parada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de Parada'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='inicio_parada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Parada'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código de Orden'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20, verbose_name='Estado de la Orden'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='maquina',
            field=models.CharField(max_length=100, verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='sintoma',
            field=models.TextField(verbose_name='Síntoma o Falla'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico_asignado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnico Asignado'),
        ),
    ]
